config/routes.rb
Rails.application.routes.draw do
  resources :confirm, only: [:confirm]
  root 'users#new'
 #resources :confirm, only: %i[new create edit update]
  post 'users/create'=>'users#create',as: 'users'
  get 'sessions/new'=>'sessions#new',as: 'login'
  post'sessions/create'=>'sessions#create',as: 'login_c'
  put 'activate/:mail'=>'auth#activate_user',as: 'activate_user'
  get 'confirm/:mail'=>'auth#confirm',as: 'confirm'
  get 'users/:id'=>'users#show',as: 'users_show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
   has_secure_password
   attr_accessor :remember_token, :activation_token
   before_save   :downcase_email
   before_create :create_activation_digest
      # 引数のハッシュ値を返す
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
    # アカウントを有効にする
  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end
  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  # ランダムトークン生成
  def self.new_token
    SecureRandom.urlsafe_base64
  end
 

  # トークンがダイジェストと一致したらtrueを返す
    def authenticated?(attribute, token)
          digest = self.send("#{attribute}_digest")
          return false if digest.nil?
          BCrypt::Password.new(digest).is_password?(token)
    end
  
   private

    # メールアドレスをすべて小文字にする
    def downcase_email
      self.email = email.downcase
    end

    # 有効化トークンとダイジェストを作成および代入する
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     include SessionsHelper
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
    
 
    def confirm
     @email =params[:mail]
    end
    def activate_user
      user=User.where('email like ?',"#{params[:mail]}%").last
      if user != nil && user.activated == nil
        user.activated = true
        user.save
        session[:user] = user
        redirect_to users_show_path(user.id)
        
      elsif user != nil &&user.activated != nil
      #flash you are already logged in.
        redirect_to root_path
      else
         #flash you are not signed in yet.
      redirect_to root_path
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end
    def create
      user = User.where(email: params[:session][:email]).last
        if user && user.activated == true && user.authenticate(params[:session][:password])
            log_in(user)
            redirect_to users_show_path(user)
        else
           flash[:warning] = "Check your email for the activation link."
           redirect_to root_url
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user=User.new
  end
  def create
    @user=User.new(user_params)
    if @user.save
       session[:user]= @user.id
       AuthMailer.send_email(@user).deliver_now
       
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user= User.find_by(id: params[:id])
  end
end
private 
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
      session[:user_id] = user.id
    end
    def logged_in?
        !current_user.nil?
    end
    def current_user
      if (user_id = session[:user_id])
        @current_user ||= User.find_by(id: user_id)
      elsif (user_id = cookies.signed[:user_id])
        user = User.find_by(id: user_id)
        if user && user.authenticated?(:remember, cookies[:remember_token])
          log_in user
          @current_user = user
        end
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MailApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "sing_up",root_path %> 
    <%= link_to "login", login_path %>
    <%= yield %>
   
  </body>
</html>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<%= form_for @user, url: users_path do |f| %>
  <p><%= f.label :name %></p>
  <p><%= f.text_field :name %></p>
  <p><%= f.label :email %></p>
  <p><%= f.text_field :email %></p>
  <p><%= f.label :password %></p>
  <p><%= f.password_field :password %></p>
  <p><%= f.label :password_confirmation %></p>
  <p><%= f.password_field :password_confirmation %></p>
    <%= f.submit :click%></p>
<% end %>

app/views/users/show.html.erb
<% if session[:user] %>
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<p>メールアドレス：<%= @user.email %></p>

<% else %>
check your email
<% end %>